spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally-quoted-identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
  sql:
    init:
      mode: always
      continue-on-error: false

logging:
  level:
    root: ERROR
    "[com.jiera.hrnetAPI]": INFO
    "[org.springframework.boot.web.embedded.tomcat]": INFO
server:
  port: 5000
